// web/src/routes/notifications/+page.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { page } from "$app/state";
	import type { SupabaseClient } from "@supabase/supabase-js";
	import { DINING_HALLS, syncFavoritedFoods, type Favorite } from "@udine/shared";
	import { IndexedDbFavoritesStorage } from "$lib/favoritesStorage";
	import { PUBLIC_VAPID_KEY } from "$env/static/public";

	type Sighting = { id: string; dish_name: string; hall_tid: number; sighted_date: string; read_at: string | null; created_at: string };

	// Standard urlBase64-to-Uint8Array conversion PushManager.subscribe needs for applicationServerKey.
	function urlBase64ToUint8Array(base64: string): Uint8Array {
		const padded = (base64 + "=".repeat((4 - (base64.length % 4)) % 4)).replace(/-/g, "+").replace(/_/g, "/");
		const raw = atob(padded);
		return Uint8Array.from(raw, (c) => c.charCodeAt(0));
	}

	function pushSupported(): boolean {
		return "serviceWorker" in navigator && "PushManager" in window && "Notification" in window && Boolean(PUBLIC_VAPID_KEY);
	}

	async function clearStoredPushTokens(supabase: SupabaseClient, userId: string) {
		// ponytail: removes every stored web token for this user, not just this browser's — fine for
		// a single-device MVP. Per-device revocation would key the delete off the known token instead.
		await supabase.from("push_tokens").delete().eq("user_id", userId).eq("platform", "web");
	}

	async function enablePush(supabase: SupabaseClient, userId: string) {
		if (!pushSupported()) return;
		try {
			const permission = await Notification.requestPermission();
			if (permission !== "granted") return;

			const registration = await navigator.serviceWorker.register("/service-worker.js");
			const subscription = await registration.pushManager.subscribe({
				userVisibleOnly: true,
				applicationServerKey: urlBase64ToUint8Array(PUBLIC_VAPID_KEY) as BufferSource,
			});
			await supabase
				.from("push_tokens")
				.upsert({ user_id: userId, platform: "web", token: JSON.stringify(subscription.toJSON()) });
		} catch (err) {
			// Permission denied, malformed VAPID key, no service-worker support in this browser, etc. —
			// notifications_enabled can still toggle for the in-app feed even if push registration fails.
			console.error("Push subscription failed:", err);
		}
	}

	async function disablePush(supabase: SupabaseClient, userId: string) {
		if (pushSupported()) {
			try {
				const registration = await navigator.serviceWorker.getRegistration();
				const subscription = await registration?.pushManager.getSubscription();
				await subscription?.unsubscribe();
			} catch (err) {
				console.error("Push unsubscribe failed:", err);
			}
		}
		await clearStoredPushTokens(supabase, userId);
	}

	const favoritesStorage = new IndexedDbFavoritesStorage();

	let notificationsEnabled = $state(false);
	let sightings: Sighting[] = $state([]);

	function hallName(hallTid: number): string {
		return DINING_HALLS.find((h) => h.tid === hallTid)?.name ?? `Hall ${hallTid}`;
	}

	async function refresh() {
		const supabase = page.data.supabase;
		const session = page.data.session;
		if (!supabase || !session) return;

		const { data: profile } = await supabase.from("profiles").select("notifications_enabled").eq("user_id", session.user.id).single();
		notificationsEnabled = profile?.notifications_enabled ?? false;

		// Browser permission can be revoked outside this page (browser settings) without us hearing
		// about it — if that happened, the stored push_tokens row is now dead, so clear it. The
		// in-app notifications_enabled flag (and food_sightings feed) is untouched either way.
		if (notificationsEnabled && pushSupported() && Notification.permission !== "granted") {
			await clearStoredPushTokens(supabase, session.user.id);
		}

		const { data } = await supabase.from("food_sightings").select("*").eq("user_id", session.user.id).order("created_at", { ascending: false });
		sightings = data ?? [];
	}

	onMount(refresh);

	async function toggleNotifications() {
		const supabase = page.data.supabase;
		const session = page.data.session;
		if (!supabase || !session) return;

		const next = !notificationsEnabled;
		await supabase.from("profiles").update({ notifications_enabled: next }).eq("user_id", session.user.id);
		notificationsEnabled = next;

		// Sync (or clear) favorited_foods to match the new state — see CLAUDE.md: favorited_foods only
		// syncs when signed in AND notifications_enabled.
		const favorites: Favorite[] = next ? await favoritesStorage.getFavorites() : [];
		await syncFavoritedFoods(supabase, session.user.id, favorites);

		if (next) {
			await enablePush(supabase, session.user.id);
		} else {
			await disablePush(supabase, session.user.id);
		}
	}

	async function markRead(sighting: Sighting) {
		const supabase = page.data.supabase;
		if (!supabase || sighting.read_at) return;
		const readAt = new Date().toISOString();
		await supabase.from("food_sightings").update({ read_at: readAt }).eq("id", sighting.id);
		sighting.read_at = readAt;
	}
</script>

<a href="/">&larr; Dining Halls</a>
<h1>Notifications</h1>

{#if !page.data.session}
	<p>Sign in to enable favorited-food alerts.</p>
{:else}
	<p>
		<label>
			<input type="checkbox" checked={notificationsEnabled} onchange={toggleNotifications} />
			Notify me when a favorited dish shows up on the menu
		</label>
	</p>
	<p><small>Turning this on will ask your browser for notification permission and register a push subscription. Server-side push dispatch is still a work in progress — see CLAUDE.md — but this page is always the notification feed.</small></p>

	<h2>Sightings</h2>
	{#if sightings.length === 0}
		<p>No favorited-food sightings yet.</p>
	{:else}
		<ul>
			{#each sightings as s (s.id)}
				<li onmouseenter={() => markRead(s)} style={s.read_at ? "opacity: 0.6" : ""}>
					<strong>{s.dish_name}</strong> at {hallName(s.hall_tid)} on {s.sighted_date}
				</li>
			{/each}
		</ul>
	{/if}
{/if}

// mobile/src/app/notifications.tsx
import { DINING_HALLS, syncFavoritedFoods, type Favorite } from "@udine/shared";
import type { Session } from "@supabase/supabase-js";
import Constants from "expo-constants";
import * as Notifications from "expo-notifications";
import { useCallback, useEffect, useState } from "react";
import { useFocusEffect } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { SqliteFavoritesStorage } from "../lib/favoritesStorage";
import { supabase } from "../lib/supabase";

const PLATFORM = "expo" as const;

/** Requests permission and returns an Expo push token, or null if denied/unavailable (e.g. no FCM creds yet). */
async function registerForPushToken(): Promise<string | null> {
  const { status: existing } = await Notifications.getPermissionsAsync();
  let status = existing;
  if (status !== "granted") {
    ({ status } = await Notifications.requestPermissionsAsync());
  }
  if (status !== "granted") return null;

  const projectId = Constants.expoConfig?.extra?.eas?.projectId;
  try {
    const { data } = await Notifications.getExpoPushTokenAsync({ projectId });
    return data;
  } catch (e) {
    // FCM credentials may not be uploaded to EAS yet — don't block the in-app feature on it.
    console.warn("[push] getExpoPushTokenAsync failed (FCM V1 creds may not be uploaded to EAS)", e);
    return null;
  }
}

type Sighting = { id: string; dish_name: string; hall_tid: number; sighted_date: string; read_at: string | null; created_at: string };

const favoritesStorage = new SqliteFavoritesStorage();

function hallName(hallTid: number): string {
  return DINING_HALLS.find((h) => h.tid === hallTid)?.name ?? `Hall ${hallTid}`;
}

export default function NotificationsScreen() {
  const [session, setSession] = useState<Session | null>(null);
  const [notificationsEnabled, setNotificationsEnabled] = useState(false);
  const [sightings, setSightings] = useState<Sighting[]>([]);

  useEffect(() => {
    supabase.auth.getSession().then(({ data }) => setSession(data.session));
    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange((_event, newSession) => setSession(newSession));
    return () => subscription.unsubscribe();
  }, []);

  const refresh = useCallback(async () => {
    if (!session) return;
    const { data: profile } = await supabase.from("profiles").select("notifications_enabled").eq("user_id", session.user.id).single();
    setNotificationsEnabled(profile?.notifications_enabled ?? false);

    const { data } = await supabase.from("food_sightings").select("*").eq("user_id", session.user.id).order("created_at", { ascending: false });
    setSightings(data ?? []);
  }, [session]);

  useFocusEffect(
    useCallback(() => {
      refresh();
    }, [refresh]),
  );

  async function toggleNotifications(next: boolean) {
    if (!session) return;
    await supabase.from("profiles").update({ notifications_enabled: next }).eq("user_id", session.user.id);
    setNotificationsEnabled(next);

    // Sync (or clear) favorited_foods to match — see CLAUDE.md: favorited_foods only syncs when
    // signed in AND notifications_enabled.
    const favorites: Favorite[] = next ? await favoritesStorage.getFavorites() : [];
    await syncFavoritedFoods(supabase, session.user.id, favorites);

    if (next) {
      // Best-effort: permission may be denied, or getExpoPushTokenAsync may fail if FCM creds
      // aren't uploaded to EAS yet. Either way, in-app notifications_enabled above still stands.
      const token = await registerForPushToken();
      if (token) {
        await supabase.from("push_tokens").upsert({ user_id: session.user.id, platform: PLATFORM, token });
      }
    } else {
      await supabase.from("push_tokens").delete().eq("user_id", session.user.id).eq("platform", PLATFORM);
    }
  }

  async function markRead(sighting: Sighting) {
    if (sighting.read_at) return;
    const readAt = new Date().toISOString();
    await supabase.from("food_sightings").update({ read_at: readAt }).eq("id", sighting.id);
    setSightings((prev) => prev.map((s) => (s.id === sighting.id ? { ...s, read_at: readAt } : s)));
  }

  if (!session) {
    return (
      <View style={styles.container}>
        <Text>Sign in to enable favorited-food alerts.</Text>
      </View>
    );
  }

  return (
    <ScrollView style={styles.container}>
      <View style={styles.toggleRow}>
        <Text style={styles.toggleLabel}>Notify me when a favorited dish shows up on the menu</Text>
        <Switch value={notificationsEnabled} onValueChange={toggleNotifications} />
      </View>
      <Text style={styles.hint}>Push delivery isn&apos;t wired up yet — this is the notification feed for now. See CLAUDE.md.</Text>

      <Text style={styles.sectionTitle}>Sightings</Text>
      {sightings.length === 0 ? (
        <Text style={styles.empty}>No favorited-food sightings yet.</Text>
      ) : (
        sightings.map((s) => (
          <Pressable key={s.id} onPress={() => markRead(s)} style={[styles.sightingRow, s.read_at ? styles.sightingRead : null]}>
            <Text style={styles.sightingText}>
              <Text style={styles.sightingDish}>{s.dish_name}</Text> at {hallName(s.hall_tid)} on {s.sighted_date}
            </Text>
          </Pressable>
        ))
      )}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, padding: 16 },
  toggleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  toggleLabel: { flex: 1, fontSize: 16 },
  hint: { color: "#888", fontSize: 12, marginTop: 8 },
  sectionTitle: { fontSize: 18, fontWeight: "600", marginTop: 20, marginBottom: 8 },
  empty: { color: "#888" },
  sightingRow: { paddingVertical: 8, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: "#eee" },
  sightingRead: { opacity: 0.6 },
  sightingText: { fontSize: 16 },
  sightingDish: { fontWeight: "600" },
});
