// mobile/src/app/rank.tsx
import { applyComparison, DINING_HALLS, favoriteDiningHalls, rankDishes, syncFavoriteHalls, type LogEntry, type RankedDish } from "@udine/shared";
import { useFocusEffect } from "expo-router";
import { useCallback, useRef, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { SqliteLogStorage } from "../lib/sqliteStorage";
import { SqliteRankingStorage } from "../lib/rankingStorage";
import { supabase } from "../lib/supabase";

type Dish = { dishName: string; hallTid: number };

const logStorage = new SqliteLogStorage();
const rankingStorage = new SqliteRankingStorage();

function hallName(hallTid: number): string {
  return DINING_HALLS.find((h) => h.tid === hallTid)?.name ?? `Hall ${hallTid}`;
}

function dishKey(d: Dish): string {
  return `${d.dishName}::${d.hallTid}`;
}

function comparisonCountFor(d: Dish, rankedDishes: RankedDish[]): number {
  return rankedDishes.find((r) => dishKey(r) === dishKey(d))?.comparisonCount ?? 0;
}

// Sample a couple of candidates and keep the least-compared one, instead of pure uniform
// random, so under-compared dishes surface more often.
function pickLeastCompared(pool: Dish[], rankedDishes: RankedDish[]): Dish {
  let best = pool[Math.floor(Math.random() * pool.length)];
  for (let i = 0; i < 2; i++) {
    const candidate = pool[Math.floor(Math.random() * pool.length)];
    if (comparisonCountFor(candidate, rankedDishes) < comparisonCountFor(best, rankedDishes)) best = candidate;
  }
  return best;
}

function samePair(p: [Dish, Dish], other: [Dish, Dish]): boolean {
  const [a, b] = [dishKey(p[0]), dishKey(p[1])];
  const [x, y] = [dishKey(other[0]), dishKey(other[1])];
  return (a === x && b === y) || (a === y && b === x);
}

function pickPair(loggedDishes: Dish[], rankedDishes: RankedDish[], exclude: [Dish, Dish] | null): [Dish, Dish] | null {
  if (loggedDishes.length < 2) return null;
  let candidate: [Dish, Dish];
  do {
    const a = pickLeastCompared(loggedDishes, rankedDishes);
    let b = a;
    while (dishKey(b) === dishKey(a)) {
      b = pickLeastCompared(loggedDishes, rankedDishes);
    }
    candidate = [a, b];
  } while (loggedDishes.length > 2 && exclude && samePair(candidate, exclude));
  return candidate;
}

export default function RankScreen() {
  const [loggedDishes, setLoggedDishes] = useState<Dish[]>([]);
  const [rankedDishes, setRankedDishes] = useState<RankedDish[]>([]);
  const [pair, setPair] = useState<[Dish, Dish] | null>(null);
  const lastPairRef = useRef<[Dish, Dish] | null>(null);

  const refresh = useCallback(() => {
    (async () => {
      const entries: LogEntry[] = await logStorage.getAllEntries();
      const seen = new Set<string>();
      const dishes: Dish[] = [];
      for (const entry of entries) {
        if (entry.source.type !== "umass-menu") continue;
        const dish = { dishName: entry.source.dishName, hallTid: entry.source.hallTid };
        const key = dishKey(dish);
        if (seen.has(key)) continue;
        seen.add(key);
        dishes.push(dish);
      }
      const ranked = await rankingStorage.getRankedDishes();
      setLoggedDishes(dishes);
      setRankedDishes(ranked);
      const next = pickPair(dishes, ranked, lastPairRef.current);
      lastPairRef.current = next;
      setPair(next);
    })();
  }, []);

  useFocusEffect(refresh);

  async function choose(winner: Dish, loser: Dish) {
    const updated = applyComparison(rankedDishes, winner, loser);
    setRankedDishes(updated);
    await rankingStorage.saveRankedDishes(updated);

    const {
      data: { session },
    } = await supabase.auth.getSession();
    if (session) {
      await syncFavoriteHalls(supabase, session.user.id, updated);
    }

    const next = pickPair(loggedDishes, updated, lastPairRef.current);
    lastPairRef.current = next;
    setPair(next);
  }

  function skip() {
    const next = pickPair(loggedDishes, rankedDishes, lastPairRef.current);
    lastPairRef.current = next;
    setPair(next);
  }

  const favorites = favoriteDiningHalls(rankedDishes);

  return (
    <View style={styles.container}>
      <Text style={styles.hint}>Compare dishes you've actually logged — ranking is built from what you've eaten, not the full menu.</Text>

      {loggedDishes.length < 2 ? (
        <Text style={styles.hint}>Log a couple of meals first, then come back here to rank them.</Text>
      ) : pair ? (
        <View>
          <Text style={styles.heading}>Which did you like more?</Text>
          <Pressable style={styles.choiceButton} onPress={() => choose(pair[0], pair[1])}>
            <Text style={styles.choiceButtonText}>
              {pair[0].dishName} ({hallName(pair[0].hallTid)})
            </Text>
          </Pressable>
          <Pressable style={styles.choiceButton} onPress={() => choose(pair[1], pair[0])}>
            <Text style={styles.choiceButtonText}>
              {pair[1].dishName} ({hallName(pair[1].hallTid)})
            </Text>
          </Pressable>
          <Pressable onPress={skip}>
            <Text style={styles.skip}>Skip</Text>
          </Pressable>
        </View>
      ) : null}

      <Text style={styles.heading}>Your ranking</Text>
      {rankedDishes.length === 0 ? (
        <Text>No comparisons yet.</Text>
      ) : (
        rankDishes(rankedDishes).map((dish, i) => (
          <Text key={dishKey(dish)} style={styles.rankRow}>
            {i + 1}. {dish.dishName} ({hallName(dish.hallTid)}) — {Math.round(dish.rating)}
          </Text>
        ))
      )}

      <Text style={styles.heading}>Favorite dining halls</Text>
      {favorites.length === 0 ? (
        <Text>Not enough ranked dishes per hall yet.</Text>
      ) : (
        favorites.map((fav) => (
          <Text key={fav.hallTid} style={styles.rankRow}>
            {fav.rank}. {hallName(fav.hallTid)}
          </Text>
        ))
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, padding: 16 },
  hint: { color: "#555", marginBottom: 12 },
  heading: { fontSize: 18, fontWeight: "600", marginTop: 20, marginBottom: 8 },
  choiceButton: { backgroundColor: "#208AEF", borderRadius: 8, padding: 14, marginBottom: 8 },
  choiceButtonText: { color: "white", fontWeight: "600", textAlign: "center" },
  skip: { color: "#888", textAlign: "center", marginTop: 4 },
  rankRow: { paddingVertical: 4 },
});

// web/src/routes/rank/+page.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { page } from "$app/state";
	import { applyComparison, DINING_HALLS, favoriteDiningHalls, rankDishes, syncFavoriteHalls, type LogEntry, type RankedDish } from "@udine/shared";
	import { IndexedDbLogStorage } from "$lib/indexedDbStorage";
	import { IndexedDbRankingStorage } from "$lib/rankingStorage";

	type Dish = { dishName: string; hallTid: number };

	const logStorage = new IndexedDbLogStorage();
	const rankingStorage = new IndexedDbRankingStorage();

	let loggedDishes: Dish[] = $state([]);
	let rankedDishes: RankedDish[] = $state([]);
	let pair: [Dish, Dish] | null = $state(null);
	let lastPair: [Dish, Dish] | null = null;

	function hallName(hallTid: number): string {
		return DINING_HALLS.find((h) => h.tid === hallTid)?.name ?? `Hall ${hallTid}`;
	}

	function dishKey(d: Dish): string {
		return `${d.dishName}::${d.hallTid}`;
	}

	function comparisonCountFor(d: Dish): number {
		return rankedDishes.find((r) => dishKey(r) === dishKey(d))?.comparisonCount ?? 0;
	}

	// Sample a couple of candidates and keep the least-compared one, instead of pure uniform
	// random, so under-compared dishes surface more often.
	function pickLeastCompared(pool: Dish[]): Dish {
		let best = pool[Math.floor(Math.random() * pool.length)];
		for (let i = 0; i < 2; i++) {
			const candidate = pool[Math.floor(Math.random() * pool.length)];
			if (comparisonCountFor(candidate) < comparisonCountFor(best)) best = candidate;
		}
		return best;
	}

	function samePair(p: [Dish, Dish], other: [Dish, Dish]): boolean {
		const [a, b] = [dishKey(p[0]), dishKey(p[1])];
		const [x, y] = [dishKey(other[0]), dishKey(other[1])];
		return (a === x && b === y) || (a === y && b === x);
	}

	function pickPair(): [Dish, Dish] | null {
		if (loggedDishes.length < 2) return null;
		let candidate: [Dish, Dish];
		do {
			const a = pickLeastCompared(loggedDishes);
			let b = a;
			while (dishKey(b) === dishKey(a)) {
				b = pickLeastCompared(loggedDishes);
			}
			candidate = [a, b];
		} while (loggedDishes.length > 2 && lastPair && samePair(candidate, lastPair));
		lastPair = candidate;
		return candidate;
	}

	async function refresh() {
		const entries: LogEntry[] = await logStorage.getAllEntries();
		const seen = new Set<string>();
		loggedDishes = [];
		for (const entry of entries) {
			if (entry.source.type !== "umass-menu") continue;
			const dish = { dishName: entry.source.dishName, hallTid: entry.source.hallTid };
			const key = dishKey(dish);
			if (seen.has(key)) continue;
			seen.add(key);
			loggedDishes.push(dish);
		}
		rankedDishes = await rankingStorage.getRankedDishes();
		pair = pickPair();
	}

	onMount(refresh);

	async function choose(winner: Dish, loser: Dish) {
		rankedDishes = applyComparison(rankedDishes, winner, loser);
		// $state arrays are deep-proxied by Svelte on assignment; IndexedDB's structured-clone can't
		// serialize a Proxy (DataCloneError), so snapshot to a plain object before persisting.
		const snapshot = $state.snapshot(rankedDishes);
		await rankingStorage.saveRankedDishes(snapshot);

		const session = page.data.session;
		if (session && page.data.supabase) {
			await syncFavoriteHalls(page.data.supabase, session.user.id, snapshot);
		}

		pair = pickPair();
	}

	function skip() {
		pair = pickPair();
	}
</script>

<a href="/">&larr; Dining Halls</a>
<h1>Rank Dishes</h1>
<p>Compare dishes you've actually logged &mdash; ranking is built from what you've eaten, not the full menu.</p>

{#if loggedDishes.length < 2}
	<p>Log a couple of meals first, then come back here to rank them.</p>
{:else if pair}
	<h2>Which did you like more?</h2>
	<button onclick={() => choose(pair![0], pair![1])}>
		{pair[0].dishName} <small>({hallName(pair[0].hallTid)})</small>
	</button>
	<button onclick={() => choose(pair![1], pair![0])}>
		{pair[1].dishName} <small>({hallName(pair[1].hallTid)})</small>
	</button>
	<button onclick={skip}>Skip</button>
{/if}

<h2>Your ranking</h2>
{#if rankedDishes.length === 0}
	<p>No comparisons yet.</p>
{:else}
	<ol>
		{#each rankDishes(rankedDishes) as dish (dishKey(dish))}
			<li>{dish.dishName} <small>({hallName(dish.hallTid)}) &mdash; {Math.round(dish.rating)}</small></li>
		{/each}
	</ol>
{/if}

<h2>Favorite dining halls {page.data.session ? "(synced)" : "(local only — sign in to sync)"}</h2>
{#if favoriteDiningHalls(rankedDishes).length === 0}
	<p>Not enough ranked dishes per hall yet.</p>
{:else}
	<ol>
		{#each favoriteDiningHalls(rankedDishes) as fav (fav.hallTid)}
			<li>{hallName(fav.hallTid)}</li>
		{/each}
	</ol>
{/if}
